In [1]:
import yfinance as yf

In [2]:
data = yf.download("2330.tw", start="2023-12-01", end="2023-12-31")
data

[*********************100%%**********************]  1 of 1 completed

             Open   High    Low  Close   Adj Close    Volume
Date
2023-12-01  573.0  579.0  573.0  579.0  573.312378  28051165
2023-12-04  582.0  582.0  571.0  574.0  568.361450  26847171
2023-12-05  571.0  572.0  567.0  570.0  564.400757  22229723
2023-12-06  568.0  575.0  568.0  570.0  564.400757  21518089
2023-12-07  570.0  573.0  566.0  566.0  560.440063  20840397
2023-12-08  574.0  577.0  570.0  570.0  564.400757  33507214
2023-12-11  572.0  575.0  570.0  574.0  568.361450  27378610
2023-12-12  580.0  581.0  575.0  578.0  572.322205  29403010
2023-12-13  576.0  579.0  576.0  577.0  571.331970  22977731
2023-12-14  581.0  582.0  579.0  582.0  579.294800  39409958
2023-12-15  585.0  586.0  580.0  585.0  582.280884  54323262
2023-12-18  579.0  585.0  577.0  585.0  582.280884  26122277
2023-12-19  588.0  588.0  580.0  585.0  582.280884  28254292
2023-12-20  587.0  587.0  583.0  585.0  582.280884  38121456
2023-12-21  577.0  579.0  575.0  577.0  574.318054  24923414
2023-12-22  582.0  582.0  579.0  582.0  579.294800  18690214
2023-12-25  582.0  585.0  580.0  581.0  578.299438   9548143
2023-12-26  583.0  586.0  582.0  586.0  583.276245  16094308
2023-12-27  587.0  592.0  586.0  592.0  589.248352  33401336
2023-12-28  592.0  593.0  589.0  593.0  590.243713  25514849
2023-12-29  589.0  593.0  589.0  593.0  590.243713  18416318

資料重新整理

In [3]:
data.reset_index()
data

             Open   High    Low  Close   Adj Close    Volume
Date
2023-12-01  573.0  579.0  573.0  579.0  573.312378  28051165
2023-12-04  582.0  582.0  571.0  574.0  568.361450  26847171
2023-12-05  571.0  572.0  567.0  570.0  564.400757  22229723
2023-12-06  568.0  575.0  568.0  570.0  564.400757  21518089
2023-12-07  570.0  573.0  566.0  566.0  560.440063  20840397
2023-12-08  574.0  577.0  570.0  570.0  564.400757  33507214
2023-12-11  572.0  575.0  570.0  574.0  568.361450  27378610
2023-12-12  580.0  581.0  575.0  578.0  572.322205  29403010
2023-12-13  576.0  579.0  576.0  577.0  571.331970  22977731
2023-12-14  581.0  582.0  579.0  582.0  579.294800  39409958
2023-12-15  585.0  586.0  580.0  585.0  582.280884  54323262
2023-12-18  579.0  585.0  577.0  585.0  582.280884  26122277
2023-12-19  588.0  588.0  580.0  585.0  582.280884  28254292
2023-12-20  587.0  587.0  583.0  585.0  582.280884  38121456
2023-12-21  577.0  579.0  575.0  577.0  574.318054  24923414
2023-12-22  582.0  582.0  579.0  582.0  579.294800  18690214
2023-12-25  582.0  585.0  580.0  581.0  578.299438   9548143
2023-12-26  583.0  586.0  582.0  586.0  583.276245  16094308
2023-12-27  587.0  592.0  586.0  592.0  589.248352  33401336
2023-12-28  592.0  593.0  589.0  593.0  590.243713  25514849
2023-12-29  589.0  593.0  589.0  593.0  590.243713  18416318